import Navbar from "@/components/Navbar";
import Container from "@/components/Container";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Container>
          <Navbar />
          <>{children}</>
          <Footer />
        </Container>
      </body>
    </html>
  );
}
